SELECT TITLE
FROM  MOVIES
INNER JOIN STARS, RATINGS, PEOPLE ON STARS.Movie_id = RATINGS.Movie_id  
and STARS.person_id = PEOPLE.id 
and RATINGS.Movie_id=MOVIES.id
WHERE PEOPLE.name="Chadwick Boseman"
ORDER BY RATING DESC
LIMIT 5;